SET NAMES 'utf8';

USE blog;

DROP TABLE IF EXISTS articulos;
CREATE TABLE articulos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(200) BINARY DEFAULT NULL,
  extracto VARCHAR(200) BINARY DEFAULT NULL,
  fecha TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  texto TEXT BINARY DEFAULT NULL,
  thumb VARCHAR(50) BINARY DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 10
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_bin;
